version: '3.7'
services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../mysidecar/:/var/www/html
    networks:
      default:
        aliases:
          - sidecar.test

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ../mysidecar/:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini